version: '3'
services:
  nginx: 
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:8000
    networks:
        n1:
         ipv4_address: 172.1.1.45
        n2:
         ipv4_address: 173.1.1.45

  your_app_1:
    image: arwamohsen/airportapp:1sttry
    container_name: airportapp
    ports:
      - 9090:8080
    networks:
            n1:
                    ipv4_address: 172.1.1.44
  your_app_2:
    image: arwamohsen/countryapp:1sttry
    container_name: countryapp
    ports:
      - 8080:8080
    networks:
            n2:
                    ipv4_address: 173.1.1.44
networks:
        n1:
                ipam:
                  config:
                      - subnet: 172.1.1.0/24
        n2:
                ipam:
                  config:
                      - subnet: 173.1.1.0/24
